services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9
    container_name: db
    ports:
      - 27017:27017

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    network_mode: bridge # comment to use Docker network